### ISSUE TITLE
Doesn't compatible with react-native 0.26

### ISSUE THREAD

**Issue by rongzhou** [xinthink/react-native-material-kit#161]
Error Info:

ExceptionsManager.js:61 Module AppRegistry is not a registered callable module.
ExceptionsManager.js:61 Super expression must either be null or a function, not undefined

**Comment by herby** [comment]
Also in Switch.js. Probably lots of other places.

Pls fix this and release 0.3.2 asap. Thanks.

**Comment by TheTekton** [comment]
Those errors are from RN v0.26.0 breaking changes for react API. I could do a PR later, if need be. Here's a zip with the changes needed for v0.26.0, if that'll help anyone.

[react-native-material-kit.zip](https://github.com/xinthink/react-native-material-kit/files/275565/react-native-material-kit.zip)

**Comment by hieupm37** [comment]
@TheTekton Does your fix work with Android? I've tried but still have this error: Super expression must either be null or a function, not undefined

**Comment by TheTekton** [comment]
@hieupm37 I didn't a chance to test on Android yesterday, sorry. My testing was limited to a project that utilizes the rnmk-demo, so I can't say it's a full fix. Can you let me know what you're getting that error with (e.g. Button.js, etc.)?

**Comment by hieupm37** [comment]
@TheTekton I can run your patch now. Maybe there are somethings wrong on my installation. Thank you very much.

**Comment by herby** [comment]
Hm, maybe this is already fixed by 97c3aab and it just needs a release?

**Comment by umarFarooque** [comment]
I am facing the same issue, tried the attached zip by @TheTekton  but still facing the same issue. I am running the project on iOS simulator and get the following response on my Xcode log.

> 2016-05-23 14:23:07.937 [error][tid:com.facebook.react.JavaScript] Can't find variable: MKButton
> 2016-05-23 14:23:07.939 [fatal][tid:com.facebook.react.RCTExceptionsManagerQueue] Unhandled JS Exception: Can't find variable: MKButton
> 2016-05-23 14:23:07.960 [error][tid:com.facebook.react.JavaScript] Module AppRegistry is not a registered callable module.
> 2016-05-23 14:23:07.961 [fatal][tid:com.facebook.react.RCTExceptionsManagerQueue] Unhandled JS Exception: Module AppRegistry is not a registered callable module.

**Comment by rushabh1191** [comment]
Any idea,when 0.26 support will be rolled out?

**Comment by umarFarooque** [comment]
I am also waiting for the same. Have halted development for Android app.

**Comment by umarFarooque** [comment]
I am also eagerly waiting for the same. I've halted designing based on Material kit and using native elements for now.

**Comment by ssomnoremac** [comment]
There's a [major breaking change](http://stackoverflow.com/a/37415044/2533864) in 26 that was only a warning in 25. All packages have to conform to the new way of importing from **both** react and react-native

**Comment by herby** [comment]
OTOH, it is pure mechanical change (a few basic things must be imported from 'react', react-native specific ones from 'react-native' as before). So, please, could you make these changes (just search over all appearances of string 'react-native' or "react-native" and fix the imports) and then issue a new release? Thanks.

Cameron Moss wrote:

**Comment by umarF** [comment]
Hey, 
I'd like to contribute and change the same. Since I'm a newbie here I would need to know the steps, which I think are as follows:

1. Clone repository
2. Make changes
3. Check if working ( by implementing the same project in my react-native project and check if it works)
4. Push request

Is that all or I need to something more too ?

**Comment by Crash--** [comment]
Use the master's branch of this repo, not the npm version. Fixes are done but not released yet.

**Comment by cablegunmaster** [comment]
Tried but still got redborders in the MKButton. (just simple code no css or style changes made).

**Comment by Crash--** [comment]
@cablegunmaster  Generally you got red borders when the project (rnmk) is not well linked to your project. Can you check this? Just `rnpm link`

**Comment by devekoperiOS** [comment]
I also have the same issue. For my both iPhone and android app, its giving me Super expression must either be null or a function, not undefined.

**Comment by andreyluiz** [comment]
:+1:

**Comment by kendepelchin** [comment]
Glad I've found this issue, was breaking my head about it

**Comment by alexprice91** [comment]
@devekoperiOS is a javascript error you get when you try to inherit from something that isn't a class. The most likely reason for that if you are upgrading to `26` is react-native no longer has the class "Component". You need to use React's Component. 

A copy from release notes:

Requiring React API from react-native is now deprecated - 2eafcd4 0b534d1

Instead of:

```
import React, { Component, View } from 'react-native';
```

you should now:

```
import React, { Component } from 'react';
import { View } from 'react-native';
```

**Comment by alexprice91** [comment]
To everyone else. Following this thread: https://github.com/xinthink/react-native-material-kit/issues/164

xinthink is going to upgrade the package this weekend.

**Comment by devekoperiOS** [comment]
@alexprice91 I have changed my code and every where I replace code that you suggested. But, still it gives me the same error.

**Comment by alexprice91** [comment]
Got it, you are going to have to wait for the next release of RNMK. If you need an update now, you can follow the instructions on this thread: https://github.com/xinthink/react-native-material-kit/issues/164

**Comment by Crash--** [comment]
I close this issue, it's a duplicate of #164  Please see this [comment](https://github.com/xinthink/react-native-material-kit/issues/164#issuecomment-222743212) to fix the problem 

If it still not working continue the discussion there.
